fix(opslevel): ensure we handle indexes starting at 1 (#11)
<!--
  !!!! README !!!! Please fill this out.

  Please follow the PR naming conventions: 

https://outreach-io.atlassian.net/wiki/spaces/EN/pages/1902444645/Conventional+Commits
-->


<!-- A short description of what your PR does and what it solves. -->
## What this PR does / why we need it

Since the OpsLevel lifecycle index starts at 1, we have to check the
slice length one greater than what we normally would.

During the last run, we got the following errors:

```
Error: is compliant for contact-extractor: unsupported lifecycle 6 End-of-life
Error: is compliant for arborist: unsupported lifecycle 6 End-of-life
```

These did not result in a real error because we allow any level for
End-of-life. But if things change in the future, we want to make sure
that we check all the levels.

<!-- <<Stencil::Block(jiraPrefix)>> -->

## Jira ID

[XX-XX]

<!-- <</Stencil::Block>> -->

<!-- Notes that may be helpful for anyone reviewing this PR -->
## Notes for your reviewers



<!-- <<Stencil::Block(custom)>> -->

<!-- <</Stencil::Block>> -->